lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%'
    public_key: '%env(JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(JWT_TOKEN_TTL)%'

    encoder:
        service:            lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: HS256

    token_extractors:

        authorization_header:
            enabled: false
            prefix:  Bearer
            name:    Authorization

        cookie:
            enabled: true
            name:    BEARER

        query_parameter:
            enabled: false
            name:    bearer
